### ISSUE TITLE
Revert without opening diff first works, but shows an error

### ISSUE THREAD

**Issue by laughedelic** [t9md/atom-inline-git-diff#5]
I see this error when I toggle Revert action with the <kbd>Alt</kbd><kbd>R</kbd> hotkey without opening the inline diff first. It does revert the change though.

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13
**Thrown From**: [inline-git-diff](https://github.com/t9md/atom-inline-git-diff) package 2.2.3

### Stack Trace

Uncaught TypeError: Cannot read property 'forEach' of undefined

```
At /Users/laughedelic/.atom/packages/inline-git-diff/lib/inline-git-diff.js:212

TypeError: Cannot read property 'forEach' of undefined
    at InlineGitDiff.revert (/packages/inline-git-diff/lib/inline-git-diff.js:212:35)
    at Function.invoke (/packages/inline-git-diff/lib/inline-git-diff.js:49:22)
    at invoke (/packages/inline-git-diff/lib/main.js:9:21)
    at /packages/inline-git-diff/lib/main.js:15:38)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -0:10.6.0 datatip:toggle (input.hidden-input)
     -0:10.3.0 inline-git-diff:revert (input.hidden-input)
     -0:10.1.0 datatip:toggle (input.hidden-input)
     -0:08.1.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -0:07.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

<details>

```
advanced-open-file 0.16.7 
antialiased 0.1.0 
ariake-dark-syntax 0.1.3 
atom-csv-markdown 1.0.2 
atom-ide-ui 0.8.1 
atom-jade 0.3.0 
atom-markdown-wrapper 5.2.2 
atom-material-ui 2.1.1 
atom-sbt-client 0.2.0 
autoclose-html 0.23.0 
autocomplete-emojis 2.5.0 
autocomplete-paths 2.12.2 
autoflow-diffable 0.5.0 
base16-syntax 1.8.1 
busy-signal 1.4.3 
cursor-history 0.13.0 
dash 1.7.1 
factoids 0.1.1 
file-icons 2.1.16 
file-types 0.5.5 
git-plus 7.10.0 
gl-light-syntax 3.0.0 
highlight-selected 0.13.1 
hyperclick 0.0.0 
hyperlink-hyperclick 1.3.4 
ide-flowtype 0.18.0 
ide-java 0.7.0 
ide-json 0.2.0 
ide-python 0.7.0 
ide-typescript 0.7.2 
inline-git-diff 2.2.3 
key-peek 0.2.12 
language-diff 0.7.0 
language-elm 1.5.0 
language-fish-shell 1.1.0 
language-gitignore 0.3.0 
language-haskell 1.17.3 
language-hocon 1.1.0 
language-latex 1.1.1 
language-pfm 0.82.0 
language-plantuml 0.2.0 
language-rdf 0.5.0 
language-roff 1.2.2 
language-scala 1.1.9 
language-sparql 0.3.0 
latex-completions 0.3.3 
line-diff-details 1.9.0 
linter 2.2.0 
linter-annotations 1.0.2 
linter-coffeescript 1.0.0 
linter-travis-lint 1.0.0 
markdown-folder 0.5.0 
markdown-preview-enhanced 0.15.2 
markdown-table-formatter 2.9.2 
mathjax-wrapper 0.1.0 
mixed-indent-warning 0.3.0 
native-ui 0.25.2 
one-dark-vivid-syntax 1.8.0 
package-manager-commands 2.0.3 
pen-paper-coffee-syntax 0.14.9 
pigments 0.40.2 
plain-simple 1.1.0 
plantuml-preview 0.12.9 
plist-converter 0.2.0 
pretty-json 1.6.4 
project-folder 1.5.0 
remember-folds 0.3.0 
set-syntax 0.4.0 
simple-align 0.2.0 
sort-lines 0.18.0 
swackets 0.35.0 
tablr 1.8.3 
teletype 0.7.0 
trailing-spaces 0.4.0 
tree-view-autoresize 2.3.0 
vim-mode-plus 1.28.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
xml-formatter 0.11.0 
```

</details>

**Comment by t9md** [comment]
Will check what’s happening.
But this is not the usecase I intended.
Revert and copy should work only after inline-git-diff enabled.

**Comment by t9md** [comment]
inline-git-diff@v2.3.0 is out

You can `revert` and `copy-removed-text` without having inline-git-diff  enabled 👍

**Comment by laughedelic** [comment]
Thanks!
